sudo: false
language: node_js
node_js:
  - "lts/*"
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_install:
  - npm update
install:
  - npm install
script:
  - npm test
  - npm run coveralls

deploy:
  provider: azure_web_apps
  skip_cleanup: true
  on:
    branch: master
    tags: true
